### ISSUE TITLE
Pinning chapter would benefit from diagram

### ISSUE THREAD

**Issue by darconeous** [rust-lang/async-book#12]
I'm trying to understand concretely how pinning works, especially in the context of `async`/`await!`, and I think that having an example with a diagram that shows exactly where everything is in memory would be extremely helpful.

I'd consider offering such a diagram, but I don't believe I grok the subject matter enough to produce one.

**Comment by darconeous** [comment]
For example, for a time I thought I understood pinning and then I saw the [implementation of `futures::executor::block_on()`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.14/src/futures_executor/local_pool.rs.html#198-201):

```
pub fn block_on<F: Future>(f: F) -> F::Output {
    pin_mut!(f);
    run_executor(|cx| f.as_mut().poll(cx))
}
```

That [`pin_mut!` macro](https://docs.rs/pin-utils/0.1.0-alpha.4/pin_utils/macro.pin_mut.html) turns out to be critical—the function doesn't compile without it. Yet I'm completely baffled by it and would never have considered that something like it might be necessary from reading the pinning chapter.

Reading up on `pin_mut!` and its implementation was not helpful in illustrating exactly what is going on:

```
/// Pins a value on the stack.
///
/// ```
/// # use pin_utils::pin_mut;
/// # use core::pin::Pin;
/// # struct Foo {}
/// let foo = Foo { /* ... */ };
/// pin_mut!(foo);
/// let _: Pin<&mut Foo> = foo;
/// ```
#[macro_export]
macro_rules! pin_mut {
    ($($x:ident),*) => { $(
        // Move the value to ensure that it is owned
        let mut $x = $x;
        // Shadow the original binding so that it can't be directly accessed
        // ever again.
        #[allow(unused_mut)]
        let mut $x = unsafe {
            $crate::core_reexport::pin::Pin::new_unchecked(&mut $x)
        };
    )* }
}
```

I know there is an underlying logic here and I feel like a diagram might be helpful to understanding.

**Comment by cramertj** [comment]
Hm, what kind of a diagram did you have in mind? The key bit is just that the pinned value stays in the same place-- it doesn't really matter where it, or anything else for that matter, is.
