### ISSUE TITLE
This book tastes phoney.

### ISSUE THREAD

**Issue by AndyJado** [rust-lang/async-book#166]
> If you're looking to start writing asynchronous Rust code, you've come to the right place.

it's just not. 

what should I know before I read this book? what do I get if I read this book? how do I read this book? 
no, not a clue, just be told to be the right place.

The book is so bad compared to "rust book", code don't run, examples don't explain themselves.

but you are so confidient in the book! Have you ever read it yourself?

**Comment by rylev** [comment]
Closing this since this conversation is not very productive. Please remember to keep the conversation productive and civil.
