### ISSUE TITLE
Shouldn't this comma be missing?

### ISSUE THREAD

**Issue by zll600** [rust-lang/async-book#187]
![image](https://user-images.githubusercontent.com/71714656/212534705-0217a4a4-3bb4-4a44-9372-dd955ea6721b.png)

Maybe `event` is the last parameter?

**Comment by Nereuxofficial** [comment]
This is rather convention as it makes it easier to extend the function arguments. [rustfmt](https://github.com/rust-lang/rustfmt) also does this automatically, so looks like a non-issue
