### ISSUE TITLE
Nested `use` statements are slightly difficult to read.

### ISSUE THREAD

**Issue by cldershem** [rust-lang/async-book#44]
I find nested use statements slightly more difficult to grok than keeping them all separate. it also uses more lines in most cases.

current:
```rust
use {
    std::{
        future::Future,
        pin::Pin,
        sync::{Arc, Mutex},
        task::{Context, Poll, Waker},
        thread,
        time::Duration,
    },
};
```

without nesting:
```rust
use std::future::Future;
use std::pin::Pin;
use std::sync::{Arc, Mutex};
use std::task::{Context, Poll, Waker};
use std::thread;
use std::time::Duration;
```

I think the latter is easier to read and understand. It also has the benefit of being easier to comment out unused imports while writing the rest of the code to silence RLS complaints.

If others feel the same way, I can send a PR.

**Comment by taiki-e** [comment]
I'd personally prefer to use the style that has a `use` statement for each crate. This is a compromise between two styles, and this is what [rustfmt's merge_imports config](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_imports) does.
