### ISSUE TITLE
Read data from hyper::body::Body with async/await

### ISSUE THREAD

**Issue by balthild** [rust-lang/async-book#6]
I've just followed the guide [Applied: Simple HTTP Server](https://rust-lang.github.io/async-book/getting_started/http_server_example.html) to set up a simple server app, and got stuck in getting data from `hyper::Body`.

I've found these posts: hyperium/hyper#1098, hyperium/hyper#1137, [A question on the forum](https://users.rust-lang.org/t/extracting-hyper-request-body-into-a-string/12723).

`body.concat()` returns an object implements `future_01::Future`, but when I `await` on it as following, the compiler throw long errors to me:

```rust
async fn serve_req(req: Request<Body>) -> Result<Response<Body>, hyper::Error> {
    println!("Got request at {:?}", req.uri());

    let url_str = "http://www.rust-lang.org/en-US/";
    let url = url_str.parse::<Uri>().expect("failed to parse URL");

    let res = await!(Client::new().get(url))?;

    let body = res.into_body();
    // Or
    // let body = req.into_body();

    // use futures_01::stream::Stream as Stream01;
    // use futures::compat::{Future01CompatExt, Stream01CompatExt};
    // use futures::stream::{Stream, StreamExt};

    // These are not working
    // let sth: Vec<u8> = await!(body.concat2());
    // let sth: Vec<u8> = await!(body.concat2().compat());
    // let sth: Vec<u8> = await!(body.compat().concat());

    Ok(Response::new(Body::from("Some response based on the data we just read")))
}
```

```
error[E0277]: the trait bound `std::result::Result<hyper::body::chunk::Chunk, hyper::error::Error>: std::iter::Extend<hyper::body::chunk::Chunk>` is not satisfied
  --> src/main.rs:34:34
   |
34 |     let b = await!(body.compat().concat());
   |                                  ^^^^^^ the trait `std::iter::Extend<hyper::body::chunk::Chunk>` is not implemented for `std::result::Result<hyper::body::chunk::Chunk, hyper::error::Error>`

error[E0277]: the trait bound `std::result::Result<hyper::body::chunk::Chunk, hyper::error::Error>: std::default::Default` is not satisfied
  --> src/main.rs:34:34
   |
34 |     let b = await!(body.compat().concat());
   |                                  ^^^^^^ the trait `std::default::Default` is not implemented for `std::result::Result<hyper::body::chunk::Chunk, hyper::error::Error>`

error[E0599]: no method named `into_awaitable` found for type `futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>>` in the current scope
  --> src/main.rs:34:13
   |
34 |     let b = await!(body.compat().concat());
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the method `into_awaitable` exists but the following trait bounds were not satisfied:
           `&futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::backward::IntoAwaitable`
           `&futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::forward::IntoAwaitable`
           `&mut futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::backward::IntoAwaitable`
           `&mut futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::forward::IntoAwaitable`
           `futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::backward::IntoAwaitable`
           `futures_util::stream::concat::Concat<futures_util::compat::compat01as03::Compat01As03<hyper::body::body::Body>> : tokio_async_await::compat::forward::IntoAwaitable`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 3 previous errors

Some errors occurred: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `tt`.
```

**Comment by PvdBerg1998** [comment]
Bumped into the same problem :(

**Comment by indiv0** [comment]
Do you guys have some more specific info on how to get around this? Using `try_concat()` doesn't seem to help.

**Comment by yoshuawuyts** [comment]
`http-service-hyper` provides a future 0.3 wrapper around Hyper that might come in useful. If you look at the internals there's quite a bit of work done to create a mapping, but depending on your use case you might just be able to use the crate as is :crossed_fingers:.

https://github.com/rustasync/http-service

**Comment by PvdBerg1998** [comment]
`await!(request.into_body().compat().try_concat()` is what I'm using @indiv0

**Comment by balthild** [comment]
I'd found out the solution later. Just do `await!(req.into_body().concat2())`.

See also: https://github.com/balthild/doh-proxy-rs/blob/master/src/server.rs#L110

**Comment by PvdBerg1998** [comment]
@balthild But isn't `concat2` futures 0.1? If that works in `await!`, you're using tokio's compat right? I don't think that will work when you switch to fut 0.3, which I highly recommend.

**Comment by indiv0** [comment]
@PvdBerg1998 my issue turned out to actually be unrelated (just with a similar error message). Thanks for the quick replies :)

**Comment by base698** [comment]
Anyone got a complete example on how this works?  I've tried BufReaders, using fold, using map, wait will block the current thread and never complete.  Would be nice to just have a .bytes() or something to be able to get the content.  

There is conflicting information all over Google and I've been basically trying random methods at this point.

**Comment by indiv0** [comment]
Is [this](https://github.com/indiv0/fomp/blob/master/src/main.rs#L39-L49) what you're looking for @base698?

**Comment by mleonhard** [comment]
This is working for me:
```rust
// main.rs
use hyper::Client;

#[tokio::main]
pub async fn main() -> () {
    let url: hyper::Uri = "http://api.ipify.org".parse().unwrap();
    println!("GET {}", url);
    let mut response = Client::new().get(url).await.unwrap();
    let body = hyper::body::to_bytes(response.body_mut()).await.unwrap();
    println!("{} {:?}", response.status(), body);
}
```

```toml
# Cargo.toml
[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = "~0.13.4"
tokio = { version = "~0.2.16", features = ["full"] }
```

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/example`
GET http://api.ipify.org/
200 OK b"136.24.133.93"
```

I spent several hours to find this solution.  The main problem is that the the code for dealing with http bodies is spread across many many many modules.  The use of re-exports, type aliases, and prelude imports make this much harder than it needs to be.  Documentation is lacking.  Google links often go to old versions of docs.  Online discussions are barely useful because the Rust and Tokio APIs have changed several times over the last few years.  Commenters rarely show the actual versions of the packages they use.

It's a mess now, but I expect it to get better.  Rust's `async` support and Tokio are still pretty new.  I'm happy that the tools exist. :)

**Comment by apiraino** [comment]
just passing by to thank @mleonhard for the clear, complete and really useful code snippet which replaces the now obsolete [suggested solution](https://github.com/rust-lang/async-book/issues/6#issuecomment-479984155).
