### ISSUE TITLE
Running long task inside async functions

### ISSUE THREAD

**Issue by 2f856a41-a84c304b-9d399ec8-80b8a99a** [rust-lang/async-book#80]
Hello Rust Developers,

I have searched the book, several times. But I couldn't find one answer for my question, which is: _Can I run a long task inside an `async` function?_

For example:

```rust
async fn long_task() {
    let data = std::fs::read(...);

    // Hash data
    // ...

    // Do some other tasks with data
    // ...
}
```

I know about `tokio-fs` crate. But my question is about that.

Thank you,

**Comment by steveklabnik** [comment]
Questions are best asked on users.rust-lang.org. Thank you!

**Comment by 2f856a41-a84c304b-9d399ec8-80b8a99a** [comment]
@steveklabnik 

I mean, it would be great if you add docs about that to the book.
