### ISSUE TITLE
Fixed workarounds - Content removal

### ISSUE THREAD

**Issue by srikwit** [rust-lang/async-book#84]
The issues:
https://github.com/rust-lang/rust/issues/54326
https://github.com/rust-lang/rust/issues/60424

mentioned in "Return type Errors" in the workaround seem to be fixed. Hence, I would like to request their removal from the section (7.1).

**Comment by taiki-e** [comment]
As for rust-lang/rust#60424: fixed in #88.

**Comment by taiki-e** [comment]
done in #107
